### ISSUE TITLE
Clean up the list 

### ISSUE THREAD

**Issue by mastermind1981** [jessicard/remote-jobs#163]
Hi,

In the current list there is clearly some companies there are not offering remote jobs.

They should be removed from the list.

**Comment by jessicard** [comment]
Do you have a list of ones that should be removed? I'd also happily accept a PR if you were able to make one!

**Comment by mastermind1981** [comment]
okay I will do iit

**Comment by numbsafari** [comment]
@jessicard - I was about to submit a PR to remove CartoDB (they have no remote jobs on their board, just office jobs in NYC or Spain). Would you prefer one PR per company (so that it's easier for them to respond/comment in the PR) or would you like one large PR with a number of companies (making it more focused for you/mainters)?

Also, I can try to use git-blame to see who originally added the company and @-mention them in the PR if you think that's appropriate.

**Comment by dougaitken** [comment]
Hi @numbsafari this has already been discussed with a current CartoDB employee. See #153 

If you would like to open a PR to remove the companies which you don't believe are remote and we can discuss from there. 

Also, I was the person who committed the company profile for CartoDB :+1:

**Comment by dougaitken** [comment]
Closing. No PRs submitted and list has changed quite a bit since then
