### ISSUE TITLE
Remote vs really remote

### ISSUE THREAD

**Issue by benschwarz** [jessicard/remote-jobs#54]
Being from Australia often has advantages and disadvantages, one question that time again stands out while looking for remote work is "how remote?" — Many U.S companies are not comfortable with someone in a different timezone. It'd be great to add some information like: 

| Company location(s) | Domestic remote | International remote |
|---------------------------|------------------------|-----------------------------|
| Melbourne, Kraków | ✅ | ✅ |

**Comment by jessicard** [comment]
Good call. Maybe these two columns would be better instead of region on the table? In the company profile, there's a section for "Remote Status" also, which may help: https://github.com/jessicard/remote-jobs/blob/master/company-profiles/example.md#remote-status. What do you think?

**Comment by benschwarz** [comment]
Hmm. The questions that I like to cover in my own head to become comfortable with a client/company is: 

* How experienced at remote are they? What do they have in place to make it work?
* Where are they? (Can I see *me* being able to deal with the timezone(s)?)
* Can I travel while I work with this company? Is that likely to be a problem?
* How often does the company get everyone together in meatspace?

… Thats all I can think of right now. I think "domestic remote / international remote" goes a long way aside from listing every timezone in the world.

**Comment by thefoxis** [comment]
+1 on that, there are many companies that say they're remote (e.g. Stripe) but only hire within US. to me that's not really remote, still restricted to a particular region.

I think it would be good to maybe add these questions to the template (just rephrasing what @benschwarz wrote really):

* How long have you been hiring remotely?
* What strategies do you use to make remote work? (ensure inclusivity and good communication)
  * Video chat 1:1s: Yes/No
  * Text communication channels: e.g. Slack, Hangouts, IRC
  * Daily Check-ins: Yes/No
  * Weekly Updates: Yes/No
* What cities and timezones are your employees at?
* Are remote employees allowed and encouraged to travel?
* How often do you organise company-wide get-togethers?

We could add more but that's just what came to my mind immediately and without :coffee:

**Comment by dougaitken** [comment]
Wishing I could add a Slack style response to this @thefoxis 

A lot of that is ringing even more for me recently after I read Zach Holman's [Remote-First vs. Remote-Friendly](http://zachholman.com/posts/remote-first/).

I think with a lot of these different options and needing more clarification, the idea of #Num: #44, and creating a Pages site with ability to filter by different requirements.

**Comment by tedmiston** [comment]
These are really good points to bring up, especially about timezones.

**Comment by tfont** [comment]
Most companies will hire within timezones rather than just regions. I would highly recommend a field for 'accepted timezones'.

**Comment by pjazdzewski1990** [comment]
In general I agree with the statements above, but ...
In order to make "Remote-friendly companies" more that just a marketing trick I would suggest encouraging companies from the list to show in what way they are friendly for remotes. 

IMO it will be extremely hard to do a one-size-fits-all solution for all companies, but if you could create a place where they could link to sites/blog posts/articles describing how they handle remote work. This way you could allow companies (and employees) to speak up, eliminate companies that only pretend and create a really useful database with information on how different companies approach working remotely. This way you could make this "working remotely" movement grow faster and better :rocket: 

Personally I wouldn't do it as a checklist - lists suggest that companies that scored better are better that those who scored lower. For instance "Video chat 1:1s" mentioned above is a poor condition to me - we don't do formalized 1:1s at all and I strongly believe that introducing them isn't connected to remote work but rather with work in general. 
These I my opinions. Hope they help :)

**Comment by reinaldob** [comment]
+1 on @pjazdzewski1990

**Comment by benschwarz** [comment]
As I said in my second comment, they're questions that float around _my_ head when talking to people, but I'm sure there is no one size fits all (within the scope of this repo) for describing how a company conducts itself. 

@jessicard I think we have consensus that it _would be great_ to cover the 'span of remoteness' — I think domestic / international is a good start, and perhaps a good indicator without getting too far into depth on checklists.  What do you think?

**Comment by useruby** [comment]
may be assume that all the companies allow a fully remote position and add column where companies can describe restrictions if position is not fully remote

comany name | .... |      restrictions        
-----------------------|-----|-------------------------------
  xxx                | .... | US candidates only, Work in the office during first two week

Timezone is usually not the main problem when company is hiring developer from oversea. I have never met clients who is required 100% coverage during company work time. Anyway company can add timezone restriction into restrictions column if they have one. Put something like: "must be available from 8 am to 6 pm EST".

**Comment by mastermind1981** [comment]
+1

**Comment by dougaitken** [comment]
I'm closing this issue as I believe this issue is covered with the way the readme lists the region. 

I know it doesn't a lot of what @thefoxis suggested but without having an employee of each company detail these, it is difficult to answer. 

If your company has remote DNA, please do submit a company-profile, or edit your own with more details under "remote status" (I'm toying with adding a "other info" section to the template)
